version: '3'

services:
  cinder-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/.Xauthority
